services:
  postgres:
    image: postgres:17
    container_name: student-employee-postgres
    environment:
      POSTGRES_DB: student_employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - student_employee_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_employee_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  student_employee_pgdata:
